# Generated by Django 5.1 on 2025-02-03 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('phone_number', models.CharField(default='', max_length=12)),
                ('email', models.CharField(default='', max_length=100)),
                ('password', models.CharField(default='', max_length=50)),
            ],
        ),
    ]
