# Generated by Django 5.1 on 2025-02-07 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('city_app', '0002_alter_user_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('description', models.TextField()),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('quantity', models.CharField(default='', max_length=50)),
                ('image', models.FileField(blank=True, null=True, upload_to='product_images')),
            ],
        ),
    ]
